### ISSUE TITLE
Composer install incorrect command in Readme

### ISSUE THREAD

**Issue by Tomdazy** [technicalguru/qrcode-php#2]
Hi ! In the readme.md you writted the command `composer install technicalguru/qrcode` instead of `composer require technicalguru/qrcode` 
Have a good day ;)

**Comment by technicalguru** [comment]
You are right. Will fix it. Thank you.

**Comment by technicalguru** [comment]
Fixed in 1.0-dev branch. Will be pushed to master branch with next release.
